version: '3.8'

services:
  # Контейнер для базы данных
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: user_reward_db               # Имя базы данных
      POSTGRES_USER: postgres                    # Имя пользователя
      POSTGRES_PASSWORD: postgres                 # Пароль пользователя
    ports:
      - "5432:5432"                              # Проброс порта для доступа к БД
    volumes:
      - pg_data:/var/lib/postgresql/data         # Хранение данных

  # Контейнер для приложения
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db                                       # Зависимость от базы данных
    ports:
      - "8080:8080"                              # Проброс порта для доступа к приложению
    environment:
      DB_HOST: db                                # Хост для подключения к базе данных
      DB_PORT: 5432                              # Порт базы данных
      DB_USER: postgres                          # Имя пользователя базы данных
      DB_PASSWORD: postgres                      # Пароль пользователя базы данных
      DB_NAME: user_reward_db                    # Имя базы данных
      SERVER_PORT: 8080                          # Порт сервера приложения

volumes:
  pg_data:                                      # Данные базы данных будут храниться в этом томе
